def component = [
        front: true,
        nginx: false,
        redis: false,
        back: false
]
pipeline {
    agent any
    environment {
        REPO = "s10-webmobile1-sub2/S10P12C204"
        VITE_AWS_ACCESS_KEY_ID = "${env.VITE_AWS_ACCESS_KEY_ID}"
        VITE_AWS_SECRET_ACCESS_KEY = "${env.VITE_AWS_SECRET_ACCESS_KEY}"
    }


    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage("Build") {
            steps {
                script {
                    sh "ls -al"
                    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'Docker-hub', usernameVariable: 'DOCKER_USER_ID', passwordVariable: 'DOCKER_USER_PASSWORD']]) {
                        sh "docker build --no-cache -t ${DOCKER_USER_ID}/front frontend"
                    }
                }
            }
        }

        stage("Login") {
            steps {
                withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'Docker-hub', usernameVariable: 'DOCKER_USER_ID', passwordVariable: 'DOCKER_USER_PASSWORD']]) {
                    sh """
                        set +x
                        echo $DOCKER_USER_PASSWORD | docker login -u $DOCKER_USER_ID --password-stdin
                        set -x
                    """
                }
            }
        }

        stage("Tag and Push") {
            steps {
                script {
                    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'Docker-hub', usernameVariable: 'DOCKER_USER_ID', passwordVariable: 'DOCKER_USER_PASSWORD']]) {
                        sh "docker push ${DOCKER_USER_ID}/front"
                    }
                }
            }
        }

        stage('Prune old images') {
            steps {
                script {
                    sh "docker system prune --filter until=1h"
                }
            }
        }
        stage('Pull') {
            steps {
                script {
                    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'Docker-hub', usernameVariable: 'DOCKER_USER_ID', passwordVariable: 'DOCKER_USER_PASSWORD']]) {
                        sh "docker pull ${DOCKER_USER_ID}/front"
                    }
                }
            }
        }

        stage('Up') {
            steps {
                script {
                    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'Docker-hub', usernameVariable: 'DOCKER_USER_ID', passwordVariable: 'DOCKER_USER_PASSWORD']]) {
                        try{
                            sh "docker rmi xogns5/front"     //images 날리기
                            sh "docker stop -f front || true"
                            sh "docker rm -f front || true"
                            sh "docker run -d --name front -p 8083:3000 \
                            -e VITE_AWS_ACCESS_KEY_ID=${VITE_AWS_ACCESS_KEY_ID} \
                            -e VITE_AWS_SECRET_ACCESS_KEY=${VITE_AWS_SECRET_ACCESS_KEY} \
                             ${DOCKER_USER_ID}/front"
                        } catch (Exception e){
                            sh "docker restart front"
                        }
                    }
                }
            }
        }
    }
    
//    post {
//        always {
//            script {
//                def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
//                def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
//                mattermostSend (color: 'good',
//                        message: "빌드 성공: ${currentBuild.currentResult} ${env.JOB_NAME} #${env.BUILD_NUMBER} by ${Author_ID}(${Author_Name})\n(<${env.BUILD_URL}|Details>)",
//                        endpoint: 'https://meeting.ssafy.com/hooks/q4qjarpscbf9pme4f46yiojzfe',
//                        channel: 'C107-Jenkins'
//                )
//            }
//        }
//    }
}


